### ISSUE TITLE
Application error when press links in About window

### ISSUE THREAD

**Issue by Mant1kor** [sergeysyrovatchenko/SQLIndexManager#8]
![зображення](https://user-images.githubusercontent.com/5281753/62277158-3a4bb680-b44e-11e9-969b-facb5bf98f3a.png)

> Application has encountered an unexpected error\r\nPlease send error detail to sergey.syrovatchenko @gmail.com\r\nBuild: 1.0.0.46\r\nOS: Microsoft Windows NT 6.2.9200.0\r\n\r\nThe system cannot find the file specified\r\nSystem\r\n   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SQLIndexManager.AboutBox.Copyright_HyperlinkClick(Object sender, HyperlinkClickEventArgs e)
   at DevExpress.XtraEditors.LabelControl.RaiseHyperlinkClick(HyperlinkClickEventArgs e)
   at DevExpress.XtraEditors.LabelControl.TryClickHyperlink(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.LabelControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The same problem with Feedback and GitHub Project links.
OS: Windows 10 Pro 1903 x64

**Comment by sergeysyrovatchenko** [comment]
Epic bug hahaha... if seriously thanks for this issue. Will fix in next build.

**Comment by sergeysyrovatchenko** [comment]
Fixed in version 1.0.0.47. Thanks for your feedback.
